version: 2.1
jobs:
  build: 
    working_directory: ~/transformation-advisor-sdk 
    docker: 
      - image: circleci/openjdk:11-jdk
    steps: 
      - checkout 
      - run: mvn clean install 
      - store_test_results:  
          path: target/surefire-reports
      - store_artifacts: 
          path: target/ta-sdk-sample-0.5.2.jar
      
